# Use official Python image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend code and configuration file
COPY src/ ./src/
COPY config.json.sample ./config.json

# Expose port
EXPOSE 5002

# Start API server
CMD ["python3", "src/api_server.py"]
